### ISSUE TITLE
Possible error in install script

### ISSUE THREAD

**Issue by andrewkshim** [spf13/spf13-vim#151]
When running the install command (curl http://j.mp/spf13-vim3 -L -o - | sh) I run into the following errors:

sh: 14: function: not found
sh: 18: Syntax error: "}" unexpected

**Comment by spf13** [comment]
What OS (and shell) are you using?

Best,
Steve

## 

Steve Francia
@spf13 (http://twitter.com/spf13)

**Comment by andrewkshim** [comment]
Ubuntu 12.04 64-bit and bash. I appreciate the quick response!

Andrew

**Comment by spf13** [comment]
Can you try it again now. I think I've fixed this.  

Best,
Steve

## 

Steve Francia
@spf13 (http://twitter.com/spf13)

**Comment by andrewkshim** [comment]
It looks like the error was fixed but now I am running into the following:

Error detected while processing /home/ark5/.spf13-vim-3/.vimrc.bundles:
line   36:
E117: Unknown function: vundle#rc
line   43:
E492: Not an editor command:         Bundle 'gmarik/vundle'
line   44:
E492: Not an editor command:         Bundle 'MarcWeber/vim-addon-mw-utils'
line   45:
E492: Not an editor command:         Bundle 'tomtom/tlib_vim'
line   77:
E492: Not an editor command:             Bundle 'scrooloose/nerdtree'Vim: Reading from stdin...

**Comment by spf13** [comment]
Can you uninstall spf13-vim and try again from the beginning?

There is an uninstaller script I just wrote (meaning it's barely been used or tested) in the distribution.  

Best,
Steve

## 

Steve Francia
@spf13 (http://twitter.com/spf13)

**Comment by andrewkshim** [comment]
Yep, everything looks to be correctly installed now. The distribution looks great, thanks for all the hard work!

Andrew

**Comment by percy507** [comment]
**Description:**

> Just now, i also meet this error.
> Error detected while processing /home/$USER/.spf13-vim-3/.vimrc.bundles:
line 36:
E117: Unknown function: vundle#rc
line 43:
E492: Not an editor command: Bundle 'gmarik/vundle'
line 44:
E492: Not an editor command: Bundle 'MarcWeber/vim-addon-mw-utils'
line 45:
E492: Not an editor command: Bundle 'tomtom/tlib_vim'
> line 77:

**What I Do:**

* Reinstall it. But still not working.
* Then i review the message after the installation. And i notice an error message says `can not establish ssh connection`.

> Then i guess maybe the network cause the error.(I am in China, use the network powered bt GFW.)
> So i add the proxy for my shell.( I use iterm2 and zsh)
> Then i add the following code to the `.zshrc`.

```bash
# add proxy server
export http_proxy=socks5://127.0.0.1:1086
export https_proxy=$http_proxy
```

Then i reinstall it again. Everything works fine. 😎
