### ISSUE TITLE
It requires Vim 7.3.885 or later with Lua support ("+lua").

### ISSUE THREAD

**Issue by cibiluozu** [spf13/spf13-vim#773]
neocomplete does not work with this version of Vim.
It requires Vim 7.3.885 or later with Lua support ("+lua").
It appear this question when open vim.

**Comment by janwirth** [comment]
you can find the installation instructions for vim with Lua support here https://github.com/Shougo/neocomplete.vim#installation

**Comment by cibiluozu** [comment]
Thank you,I find answer in there,I need 
    vim-nox
    vim-gtk
    vim-gnome
    vim-athena

**Comment by FranzSkuffka** [comment]
close the issue, maybe?

**Comment by ghost** [comment]
I'd like to wait until @spf13 weighs in on whether we should actually require a vim with +lua.

If we do require +lua, then we should adapt the bootstrap.sh script to error out right away if vim is missing support for it.

**Comment by diraol** [comment]
@cibiluozu you just need vim-nox, you don't need to install the other packages!

**Comment by spf13** [comment]
We shouldn't require +lua. We should take advantage of it if it's present, but spf13-vim should work with pretty much any stock vim on any given distribution (most of which don't include +lua).

**Comment by spf13** [comment]
I think the issue is that neocomplete is now the default and it requires +lua. It probably shouldn't be the default, or we could even put a conditional around it to detect if +lua is present and if not, fall back to neocomplcache.

**Comment by cibiluozu** [comment]
Thank you, @diraol you are right~

**Comment by yehh** [comment]
I encounter the problem, and need to get the corrsponding Vim with Lua support and follow the instructions.

**Comment by alexche8** [comment]
I just downloaded https://github.com/Shougo/neocomplcache.vim to my .vim/bundles/ directory and rename it neocomplete.vim

**Comment by ghost** [comment]
Oddly, I've followed the advice at https://github.com/Shougo/neocomplete.vim but still the /usr/bin/vim seems to be the un-lua version?

**Comment by cocobear** [comment]
- On Windows you should follow this instruction:

**Note:** the Vim build may not include the Lua DLL. In that case,[download Lua](http://lua-users.org/wiki/LuaBinaries) and put the `lua52.dll` file in the same directory as `gvim.exe`.

**Comment by Halfish** [comment]
On my Ubuntu 15.04, I solved this problem by this following command,

``` shell
$ sudo apt-get install vim-nox
```

**Comment by yinsang** [comment]
On Windows you should follow this instruction:
in gvim:
 `:lua print('x')`
to see which lua do you need.
this time 。
`:echo has("lua")` returns 0;
go to [lua website](https://sourceforge.net/projects/luabinaries/files/) to download the version you need.
compresses，and put *.dll to the folder beside gvim.exe 
this time 。
`:echo has("lua")` returns 1;
Done !
:》

**Comment by Wkee** [comment]
how to solve this on mac?
in vim:
`:echo has("lua")` and it returns 1;
but the problem still exists.
P.s. my vim version is 8.0.1175.

**Comment by DeepWoods** [comment]
@Wkee If you upgraded vim with homebrew on OS X, you may have missed including lua with the build.  I had to reinstall vim to include lua before it worked even though `:echo has("lua")` returned 1 as well.  This fixed my problem:
 
`brew reinstall vim --with-lua --with-override-system-vi`

**Comment by s-ertugrul** [comment]
thank you!

**Comment by Anogoya-Dagaate** [comment]
FWIW - Don't rename the lua54.dll into the version label required by your system [lua53.dll in my case]. It won't play nice. Instead follow @yinsang instruction to detect your specific version and locate it by drilling down into the version folders at the download links. Also check whether you are running 64-bit compiled Vim. Don't ask how I learned any of this.

**Comment by keithpickett** [comment]
The  (Windows 10 solution) solution provided by @yinsang worked for me here in April 2021.  Thank you!

**Comment by ErrorNoInternet** [comment]
> On my Ubuntu 15.04, I solved this problem by this following command,
> 
> ```shell
> $ sudo apt-get install vim-nox
> ```

Is there a solution for Arch Linux? I can't seem to find the package...
